### ISSUE TITLE
headphone jack

### ISSUE THREAD

**Issue by dbookuz** [lersy/Dell-7577-Hackintosh-macos-Opencore#6] opened 2020-05-28 11:59 UTC
Good day! I just created this account just for this wonderful efi, it helped me boot my first OC without having too much knowledge of it. I just copied everything from ur EFI and ofcourse i change the SMBIOS to have my own serial etc etc.. only problem im seeing now is the headphone jack. Is there a fix for this sir? And do I still need to do the post installation, the filevault etc? Thanks sir, i'm new to OC and came from clover. I have the i5-7300 version of 7577 and used the 14,3 too!

**Comment by lersy** [comment] 2020-05-29 17:29
Hey buddy. Thanks for your comment. I am glad that it helps you to boot macOS. 

headphone jack is something I forgot because I haven't used it with my pc for more than a year. Right now I am away from my home and it will take approximately two weeks to go back. I have no headphone to try the results. 

I was able to use my headphone jack with codec commander and hda-verb in the past. but I can give you a suggestion to try. When I have a chance, I will fix it and upload the solution in case it does not work.

change your layout id to 13 or 21 and give it a go if it works or not.

if it does not work, add below ssdt to your acpi folder and add it into your config.plist as well and see results.

[SSDT-ALC256.aml.zip](https://github.com/lersy/Dell-7577-Hackintosh-macos-Opencore/files/4703183/SSDT-ALC256.aml.zip)

if  not, you can try "verbstub.kext". google verbstub alc256 and follow a guide's instruction. 

there is no pre or post installation you can use this efi with installing, upgrading, booting Mac OS as it is. but for FileVault you should tweak a couple of quirks in config.plist you can read required quirks from dortania open core guide. 

personally I do not use OC with GUI so I disable showpicker. Also I do not use bluetooth firmware kexts because they drain battery a little bit faster. I can have 3 hours on screen time with watching YouTube videos. 

Smbios should be fine with your cpu model. if you are ok with it and using iMessage FaceTime stuff I do not recommend to change it. if you don't, you can try other smbios but I think no need.

keep me updated if you find a solution to headphone jack bro. have a good day.

**Comment by dbookuz** [comment] 2020-05-29 23:50
thanks for the reply sir! will definitely try that for the headphone jack. i'm good with having no post installation or something with this EFI as im new to OC and is very complicated for me but im still reading alot of it. Bluetooth is fine sir, as long as i can connect my airpods or speaker and the battery can last me for 3-4hrs i think, not bad. Yeah i think the smbios is fine, because I can use Find My and open facetime and imessage, only problem is it cannot sync all my contacts as I dont have someone to test them..

I'll keep u updated sir regarding the headphone jack fix, thanks sir and have a good day

**Comment by dbookuz** [comment] 2020-06-02 02:05
good day again, I tried changing my layout id to 13 or 21 but nothing happens. Also tried the alc256 verbstub kext method and still nothing happens. I'm not sure how to do the SSDT method.. anyways, it's not a big of a deal.. hoping you still develop this on future releases on our 7577! Thanks sir

**Comment by lersy** [comment] 2020-06-12 10:54
hey mate

for me simply setting layout id to 21 does the trick. both internal speakers and headphone audio work without any other kext, ssdt or exec file. 

can you upload your current efi? how did you change layout-id? you should open config.plist with a proper plist editor ( I use plistEdit pro ) and head to device properties > add > PciRoot(0x0)/Pci(0x1f,0x3) expand it you will see layout-id section. it should be set to 15000000 

it works me directly but right now I am not quite sure for long term usage. I will try this layout-id and from now on this will be default if there is no other issue. 

please update me with your results. 

have a good day.

**Comment by dbookuz** [comment] 2020-06-12 11:07
just tried it now sir and it works, hopefully this will work long term.. may I ask if you plan to develop this hackintosh on our 7577 on future releases? thank you again sir and have a good day

**Comment by lersy** [comment] 2020-06-12 11:52
I am glad that it works you too as well. Use it for a couple of days and note different usage scenarios like after sleep wake plugging and unplugging again and again. if you encounter a problem please let me know so we can try to fix it if it is possible. if you have no problems at all, please inform me again.

I will try to upload an efi folder once a month when acidanthera team goes back to development. Acidanthera is the team behind the OpenCore project and they will be off for two months to take of a break. Since we have no problem to boot macOS Catalina now , nothing will be improved besides minor issues like this headphone jack. if there will be a chance, I will give it a look when new macOS version release.

**Comment by dbookuz** [comment] 2020-06-12 12:26
wouldn't a reboot fix itself if that problem occurs? i'll be around for a long time as this is will be my laptop for another year i think and for sure will inform if anything happens sir..

yea i heard that too, no worries as this efi is running smooth for the past 3 weeks.

**Comment by lersy** [comment] 2020-06-12 13:16
a reboot would fix it but if there is a chance to omit this rebooting part we should give it a go. when it works , it works most of the time but situations like after waking up can cause problem from time to time. I will have this laptop for at least two years ahead so I will be interested in macOS in this time as well. 

Oc is pretty straightforward. It really has a clean base so I believe it will work flawlessly when you configured it fully for once.

**Comment by dbookuz** [comment] 2020-06-27 02:21
have u tried installing big sur yet on our 7577? i'm seeing guides here and there but i'm not ready to risk it just yet lol

**Comment by lersy** [comment] 2020-06-28 12:36
I haven't tried it yet. I have no plan to try in near future. It is in early developmental stages now and I do not have a separate drive to give it a go. Is there any significant feature to take risk now? 

By the way, what about headphone jack? Does latest ID work as intended for you? If so, from now I will stick to this audio ID. For me It has no issues so far but I have rarely used my headphone.

**Comment by dbookuz** [comment] 2020-06-28 15:53
oh no worries, just asking.. i think it's not worth it yet to update to Big Sur as of now as i have seen many with tons of bugs. It's rare to see with everything working

yes the latest ID work and haven't encountered any problems since I changed it.. thank you sir.

**Comment by lersy** [comment] 2020-06-30 00:15
it is better to update BIOS when there is a new update. When I updated mine, I had no problem with macOS booting. Take a back up before to be on the safe side of course. maybe it can break things for you. be careful with your data dude if you have personal data on it.

**Closed** 2020-07-18 19:16 UTC

**Comment by abbasabidi85** [comment] 2021-04-09 08:36
thank you @lersy the layout-id 21 for ALC256 has been working pretty fine headphone jack too without any static noise the only issue I'm facing is my headphone's microphone is not working ..it's being shown up as "Line-in" but there's no activity in it...
