### ISSUE TITLE
Apple services

### ISSUE THREAD

**Issue by Ali-Fayed** [lersy/Dell-7577-Hackintosh-macos-Opencore#18] opened 2020-11-17 23:16 UTC
I updated my system to big sur and don't have any problem but i want to use imsg and apple tv and facetime they don't want to play 
Any help 

Dell 7577 
Opencore 0.6.3

**Comment by DeMikeyyy** [comment] 2020-11-18 16:49
> I updated my system to big sur and don't have any problem but i want to use imsg and apple tv and facetime they don't want to play
> Any help
> 
> Dell 7577
> Opencore 0.6.3

Hi, I can't say a solution. However, did you update from Catalina to Big Sur without problem with the November update EFI? I tried the same but the installation got stuck and I bricked my installation.

**Comment by alifayed266** [comment] 2020-11-18 16:54
I don't use november efi i updated my macos from the software update option after that i put some kexts to EFI folder to solve wifi,ethernet,audio problems now it's works fine

Not working : 
Facetime
Imessage
Touchid
Appletv
Airdrop

**Comment by lersy** [comment] 2020-11-18 18:03
Hey @alifayed266 

There is no way to use TouchID ( at least for now ) because Apple does not allow third party devices to use fingerprint

Airdrop is under development and not functioning right now as well. 

In terms of FaceTime and iMessage, I can use them without a problem. I have no idea about AppleTV because I do not have a subscription. 

This issue is related with SMBIOS parameters. Are you sure that you configured them correctly?

And if you try too many different smbios values within same ROM and router ip address , Apple can blacklist your appleid. 

If you see "call apple customer service" warning with a customer code , there is no way but calling Apple to unblock your id from their servers. Before that ensure that you configured and cleaned your smbios parameters

I hope this help you for now, if you need more help, explain your situation in a wider way

**Comment by DeMikeyyy** [comment] 2020-11-18 18:30
@alifayed266

Could you confirm which EFI folder you used?

**Comment by lersy** [comment] 2020-11-18 18:49
@alifayed266 yes dude , can you share your current EFI folder as it is except from Platformprofile ( SMBIOS ) values? 

thanks in advance

@DeMikeyyy bro if you have problems in installation phase, I am not sure if it is related to open core. Have you checked that is there a file called CtlnaAHCIport or Sata100 in kexts folder? 
This is the only thing that caused me problem while it is installing on hard disk.

**Comment by alifayed266** [comment] 2020-11-18 18:56
[config.plist.zip](https://github.com/lersy/Dell-7577-Hackintosh-macos-Opencore/files/5562092/config.plist.zip)

efi like your 0.6.3 open core ver

**Comment by lersy** [comment] 2020-11-18 19:10
@alifayed266 do you have sleep problems with this EFI or it works ok?

**Comment by alifayed266** [comment] 2020-11-18 19:15
no

**Comment by DeMikeyyy** [comment] 2020-11-18 19:17
@alifayed266 thanks
@lersy I am succesfully installed Big Sur right now. Some issues I faced:
-shutdown issue was caused by CFG lock. I had this issue before, everytime when changing CFG lock so I had to actually open up the laptop and remove the CMOS battery 😂
- when I booted to installer, stuck on grey screen. Fixed by removing prev:keyboard from config.plist
- installer didn't show in OC menu (no drives displayed while it did before with exact same EFI) fixed by setting ScanPolicy 0

Really weird @alifayed266 could upgrade with the latest  0.6.3 Catalina EFI and me not (bricked and lost macOS so I had to use gibmacos to download on Windows which could explain OC not showing drives in USB installer) so this makes me think your previous EFI was fine and it's related to fooling around to much with my laptop.

Out of curiosity, I'm gonna install Catalina again and try if it upgrades to Big Sur without issue like @alifayed266. I'm also gonna try install Big Sur with your previous EFI also out of curiosity, but finally gonna use your latest release for my final Big Sur install ofcourse. 

This has been really time and energy consuming and made me doubt if I wanted to continue using Hackintosh and don't wanna clean install every upgrade as I have lot's of programs installed but I'm almost there!
I can only admire your project and knowledge, I tried it myself some time ago with the Dortania guide, but power management and sleep/USB mapping were the only things I never got working and lot's of SSDT's were not in my EFI and looking it up on Google I never found the solutions so respect and thanks for making this possible 👍

**Comment by lersy** [comment] 2020-11-18 19:28
@DeMikeyyy bro I am glad that you managed to boot it again but I am afraid you will lose it again :)

Right now, my efi folder actually is fulled with SSDTs and I am trying to polish it. Most probably by today next month there will be no problem left. Theoretically  Efi folder should work fine , but I will be focusing more on enabling it from oldest macOS to newest one yet with Apple policy to change things from version to version, it will be better to downgrade up to Mojave or high Sierra at max. Since myself is curious about latest one, I am leaving the previous macOS version behind most of the time but it is no good for everyone. 

In terms of power management , I am thinking going back to MacBookpro14,3 smbios again because it was better and I use no thunderbolt devices.

**Comment by DeMikeyyy** [comment] 2020-11-18 19:44
@lersy I just tried to boot Big Sur again with your latest 0.6.3 OC EFI and @alifayed266 config.plist to replicate the exact same EFI of him and it kernel panics, doesn't boot. Boots fine with your latest EFI. So I can't understand how @alifayed266 can even boot BS on that EFI, let alone have working Power Management lol. This really makes my head hurt lol

Also, I noticed when changing SMBIOS to MacBookPro15, or even 14.3 in confih.plist and USBMap.kext makes USB C hdmi freeze the system again so just something you know now, HDMI only works with 0x0001659 and MacBookPro14.1 

Cheers!

**Comment by alifayed266** [comment] 2020-11-18 19:49
![Screen Shot 2020-11-18 at 9 49 31 PM](https://user-images.githubusercontent.com/72504852/99580277-f46e8500-29e7-11eb-8edc-1542c8945b21.png)

**Comment by alifayed266** [comment] 2020-11-18 19:49
I will upload my fu EFI that worked for me

**Comment by alifayed266** [comment] 2020-11-18 20:02
https://drive.google.com/file/d/1PoFBZtWBj1fdAIRgYyTExEf0MmlywOUA/view?usp=drivesdk

**Comment by DeMikeyyy** [comment] 2020-11-19 11:43
@alifayed thanks I will try it tomorrow. Also I suggest to delete your picture because it shows your serial

@lersy I'll get back to you what EFI's work and which doesn't

**Comment by dbookuz** [comment] 2020-11-20 02:54
> @alifayed thanks I will try it tomorrow. Also I suggest to delete your picture because it shows your serial
> 
> @lersy I'll get back to you what EFI's work and which don't work

have u tried using the efi above bro?

**Comment by lersy** [comment] 2020-11-20 09:33
Hey you all guys,

This is a strange thing for real. at our side with alifayed , there is no problem with Big Sur. I will drop a more minimalist efi folder to just install Big Sur first, then maybe switch off the efi folder for post install again when you are done. 

My sleep problems are related to airportitlwm and bluetooth kexts I believe. When it is updated , there will be no problem. Unluckily , there was a version works with sleep but I removed it and can't find it now because code was updated. 

Be patient and we will manage it sooner or later. 

By the way we are out of topic too much, I will create a pinned "General discussion and Q&A" issue so we can talk there. 

@alifayed266 dude have you solved your problem with iMessage etc.? Give me more details of your situation and let's dive into it from now on in this discussion.

**Comment by alifayed266** [comment] 2020-11-20 10:39
No I don't fixed it 
I changed my sim 6 times in 50 days 
If my apple id will not be blocked i will fixed it because i have iphone too :/
If you have safe fix give me

**Comment by lersy** [comment] 2020-11-20 10:58
@alifayed266 I can assure that there will be no problem about your Apple ID with your iPhone. You can safely use your iPhone with all apple services no matter what you do on macos side as far as I know.
But since you pinged apple servers with so many incorrect smbios values, now they are suspicious about your Apple ID. 

Have you checked this detailed guide about iMessage fix before? https://www.tonymacx86.com/threads/how-to-fix-imessage.110471/

It explains so many things in detail. Read it.

My suggestion is like this:

1) Remove Apple ID from your macOS ( if it is ok with you, I can recommend a clean install of macOS with cleaning NVRAM at the beginning )

2) Create totally a new SMBIOS and make sure that it is unique and created by you. Do not copy from anywhere else. You can use Gensmbios. Google it you will find on GitHub by corpnewt. Your ROM address is super important. Create a new ROM address and do not use your wifi or ethernet card MAC address. 

3) Restart your router if you do not have a static IP. Even better, try to login on a different router after installation. Visit your friends or relatives IDK but if you connect to another one than your own, it is better believe me.

4) If you manage it, never ever share or change your smbios values again to avoid such problems.

Sometimes Apple servers can unblock false apple ids in a month or two. 

I hope this helps.

**Comment by lersy** [comment] 2020-11-20 11:02
@DeMikeyyy @dbookuz guys here is the minimalist EFI I mentioned. I checked this EFI with a USB 2 stick on my side and there is no problem.

If you keep having problems, you can give an update to your bios. Mine is 1.11.0

[EFI.7z.zip](https://github.com/lersy/Dell-7577-Hackintosh-macos-Opencore/files/5573084/EFI.7z.zip)

**Comment by DeMikeyyy** [comment] 2020-11-21 13:38
@lersy @alifayed266 I've been quite busy these days but I'll use your minimalist EFI for my new BS install. I'll get back to you in the Q&A thread :)

**Comment by alifayed266** [comment] 2020-11-26 03:37
@lersy please can you tell me how to raise my cpu performance by cpufirendprovider i think the performance is low

**Comment by lersy** [comment] 2020-11-26 14:56
@alifayed266 have you tried without cpufriend and cpufrienddataprovider ? 

Disable these two kexts in config.plist and disable intel step speed and speed shift in bios.

Without these , if you are satisfied with result, we can prepare a new cpufrienddataprovider for you.

**Closed** 2021-10-30 06:23 UTC
